#!/usr/bin/env bash
is_running() {
    if [[ "$2" == "node" ]]; then
        script=$(ps -ef | grep 'node' | grep $1)
    else
        script=$(ps -ef | grep 'bash' | grep $1)
    fi
    if [[ -z "$script" ]]; then
        $1 &
    fi
}

is_running 'easy_always.sh'
is_running 'gameon.mjs' 'node'
santos_calendar.py &

wlsunset -t 4000 &
pamixer --set-volume 30 &
systemctl --user import-environment PATH &
dunst &
/usr/lib/polkit-kde-authentication-agent-1 &
swayosd-server &
ianny &
wl-paste --type text --watch cliphist store &
is_music.py &
sway-audio-idle-inhibit &
wdisplays --gapplication-service &
# This is for sway to fix a game resolution issue because of a VGA as primary monitor
xrandr --output VGA-1 --primary &
swayidle -w &
#xremap ~/.config/xremap/config.yml --mouse &
