#!/usr/bin/env bash
app2unit -- waybar &
app2unit -- pavucontrol &
app2unit -s b -- gameon &
app2unit -s b -- upmon &
app2unit -s b -- easyeffects --gapplication-service &
app2unit -s b -- gammastep -P -O 2500 &
app2unit -s b -- earphone.sh &
app2unit -s b -- whatsap_on.sh &
app2unit -s b -- dunst &
app2unit -s b -- is_music &
#app2unit -s b -- sway-audio-idle-inhibit &
app2unit -s b -- swayidle -w &
app2unit -s b -- syncthing &
app2unit -s b -- killall pavucontrol &
app2unit -s b -- pamixer --set-volume 30 &
#uwsm app -- easy_always.sh &
systemctl --user import-environment PATH &
/usr/lib/polkit-kde-authentication-agent-1 &
wl-paste --type text --watch cliphist store &
