#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"
text="00:00"
COUNTDOWN="/tmp/countdown_timer"

if [[ -e "$COUNTDOWN" ]]; then
    state="warning"
    text=$(cat "$COUNTDOWN")
fi

output=$(get_pango "TIK" "$text")
printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$text" "$state"
