#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"
text="20"
COUNTDOWN="/tmp/countdown_timer"

if [[ -e "$COUNTDOWN" ]]; then
  #  state="warning"
  text=$(cat "$COUNTDOWN")
fi

output=$(get_pango "CTD" "$text")
printf '{"text": "%sM", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$text" "$state"
