#!/usr/bin/env bash
source $HOME/.config/waybar/custom_widgets/config

state="normal"

text=""
focused_output=$(niri msg --json workspaces | jq -r '.[] | select(.is_focused == true) | .output')

if [[ $focused_output == $1 ]]; then
  state="block"
  text="-"
fi

output=$(get_pango "" "$text")
printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$text" "$state"
