#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"

home=$(df -h /home/ | awk 'NR==2 {print $4}' | tr -d 'G' | tr ',' '.')

if awk "BEGIN {exit !($home < 10)}"; then
  state="warning"
fi

homefs=$home"G"
output=$(get_pango "HOM" "$homefs")
printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$home" "$state"
