#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"
text="0:00:00"
POMO_START="/tmp/pomo_timer"
POMO_PAUSE="/tmp/pomo_pause"

if [[ -e "$POMO_START" ]]; then
    text=$(cat "$POMO_START")
    if [[ -e "$POMO_PAUSE" ]]; then
        state="warning"
    fi
fi

output=$(get_pango "POM" "$text")
printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$text" "$state"
