#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"
preset=$(dconf read /com/github/wwmm/easyeffects/last-loaded-output-preset)
text="EQ"

if [[ "$preset" == "'HeavyBass'" ]]; then
  text="MUS"
  state="warning"
fi

output=$(get_pango "DSP" "$text")
printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}\n' "$output" "$preset" "$state"
