#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"
mode=$(swaymsg -t get_binding_state | jq -r '.name')
text="${mode:0:3}"
text_uppercased="${text^^}"

if [[ "$text_uppercased" != "DEF" ]]; then
  state="warning"
  output=$(get_pango "MDE" "$text_uppercased")
else
  state="hidden"
fi

printf '{"text": "%s", "tooltip": "Updates: %s", "class": "%s"}' "$output" "$mode" "$state"
