#!/usr/bin/env bash

source $HOME/.config/waybar/custom_widgets/config

state="normal"

temp=$(awk '{print $1/1000}' /sys/class/thermal/thermal_zone2/temp)

if [[ "$temp" -ge 80 ]]; then
  state="warning"
fi

output=$(get_pango "CPT" "$temp°C")
printf '{"text": "%s", "tooltip": "Temperatura: %s°C", "class": "%s"}\n' "$output" "$temp" "$state"
