#!/usr/bin/env bash
xrandr --output DP1 --off --output HDMI1 --primary --mode 1280x1024 --pos 0x168 --rotate normal --output VGA1 --mode 1360x768 --pos 1280x0 --rotate right --output VIRTUAL1 --off &
redshift -oP -O 2000 -b 1 &
nitrogen --restore &
easyeffects --gapplication-service &
unclutter &
