#!/usr/bin/env bash

easy=$(pidof 'easyeffects')
volume_status="/tmp/volume_changed"

if [[ -z "$easy" ]] && [[ ! -f "$volume_status" ]]; then
  echo "volume changed to 30% because easyeffects is not currently running"

  pamixer --set-volume 30
  touch "$volume_status"
else
  if [[ -f "$volume_status" ]] && [[ -n "$easy" ]]; then
    rm "$volume_status"
  fi
fi
