#!/usr/bin/env bash

xremap=$(pidof 'xremap')
keyboard=$(lsusb | grep "Tech Gaming")

if [[ -z "$keyboard" ]]; then
  if [[ -n "$xremap" ]]; then
    systemctl --user stop xremap.service
    echo "xremap service was stopped because the keyboard was disconencted"
  fi
else
  if [[ -z "$xremap" ]]; then
    systemctl --user start xremap.service
    echo "xremap service was started again because the keyboard was connected"
  fi
fi
