#!/usr/bin/env bash

music_app=$(pidof 'youtube-music')
music_preset_path="/tmp/music"
music_preset="HeavyBass"
equalizer_preset_path="/tmp/equalizer"
equalizer_preset="LoudnessEqualizer"

if_rm_file() {
  if [[ -f "$1" ]]; then
    echo "removing $1 file"
    rm "$1"
  fi
}

change_preset() {
  touch "$1"
  /home/cie/.bin/easy_preset.sh "$2"
  echo "applying the $2 preset"
}

if [[ -n "$music_app" ]]; then
  if [[ ! -f "$music_preset_path" ]]; then
    change_preset "$music_preset_path" "$music_preset"
    if_rm_file "$equalizer_preset_path"
  fi
else
  if [[ ! -f "$equalizer_preset_path" ]]; then
    change_preset "$equalizer_preset_path" "$equalizer_preset"

    if_rm_file "$music_preset_path"
  fi
fi
