#!/usr/bin/env bash
#waybar &
easyeffects --gapplication-service &
pavucontrol --gapplication-service &
wsunset -t 4000 &
dunst &
niriwake &
/usr/lib/polkit-kde-authentication-agent-1 &
wl-paste --watch cliphist store &
systemctl --user import-environment PATH &
nwg-wrapper -s sysinfo.sh -c sysinfo.css -r 1000 -p right -mr 50 -a start -mt 50 -j right

# This is for fixing the audio cracking while using Easyeffects on games.
pw-metadata -n settings 0 clock.force-rate 48000 && pw-metadata -n settings 0 clock.force-quantum 1024 &
