#!/usr/bin/env bash
run_unit() {
  if [[ "$2" == "gui" ]]; then
    app2unit -s a -- $1 &
  else
    app2unit -s b -- $1 &
  fi
}

# Opening pavucontrol solve an audio issue i'm having at boot.
#sleep 5 && pavucontrol &

#run_unit waybar
#run_unit swayforth
run_unit gameon
run_unit "easyeffects --gapplication-service"
run_unit "pavucontrol --gapplication-service"
run_unit "gammastep -P -O 2500"
run_unit whatsap_on.sh
run_unit dunst
#run_unit is_music
run_unit "swayidle -w"
run_unit syncthing
run_unit /usr/lib/polkit-kde-authentication-agent-1
run_unit "wl-paste --type text --watch cliphist store"
run_unit "systemctl --user import-environment PATH"
#run_unit killpavu
swaybg -i ~/.wallpapers/ign_unsplash32.png &

# This is for fixing the audio cracking while using Easyeffects on games.
pw-metadata -n settings 0 clock.force-rate 48000 && pw-metadata -n settings 0 clock.force-quantum 1024 &
nwg-wrapper -s usage.sh -c usage.css -r 1000 -p right -mr 20 -a end -mb 20 -j right -o DVI-D-1 &
