#!/usr/bin/env bash

while true
do
    monitor=$(i3-msg -t get_tree | jq -r '.. | objects | select(.focused? == true).output')
    if [ ! -e "/tmp/current_mon" ]; then
        echo "$monitor" > /tmp/current_mon
        echo "file was created"
    fi
    main_monitor=$(cat /tmp/current_mon)
    if [[ "$monitor" != "$main_monitor" ]]; then
        polybar-msg action secondary_mon hook 0
        polybar-msg action main_mon hook 0
        echo "$monitor" > /tmp/current_mon
        echo "Polybar was updated"
    fi
    sleep 1
done
