#!/usr/bin/env bash

TMP_FILE="/tmp/waybar_clock.json"

while true; do
  day=$(date +%d)
  hour=$(date +%H:%M)
  weekday=$(date +%a)
  text="$hour $day $weekday"
  short="$hour"

  echo '{"full": "'"$text"'", "short": "'"$short"'", "tooltip": "Clock", "class": "normal"}' >"$TMP_FILE"

  sleep 60
done
