#!/usr/bin/env bash
state=0
volume=""

while [[ true ]]; do
  lowfi_status=$(playerctl -p lowfi status)
  cmus_status=$(playerctl -p cmus status)
  if [[ $lowfi_status == "Playing" ]] || [[ $cmus_status == "Playing" ]]; then
    if [[ $state == 0 ]]; then
      echo "playing"
      volume=$(pamixer --get-volume)
      easyeffects -l "Bass"
      state=1
    fi
  else
    if [[ -n $(pgrep -f lowfi) ]] || [[ -n $(pgrep -f cmus) ]] && [[ $state == 1 ]]; then
      echo "paused"
      pamixer --set-volume $volume && easyeffects -l "LoudnessEqualizer"
      state=0
    fi
  fi

  sleep 1
done
