#!/usr/bin/env bash

MUSIC_PRESET="MUS"
EQUALIZER_PRESET="EQ"
EQUALIZER_PATH="/tmp/$EQUALIZER_PRESET"
MUSIC_PATH="/tmp/$MUSIC_PRESET"
echo "$EQUALIZER_PRESET" >/tmp/current_preset

while true; do
  cmus_playing=$(cmus-remote -Q | grep playing)

  remove_file() {
    if [[ -e "$1" ]]; then
      rm "$1"
    fi
  }

  set_preset() {
    jamesdsp --load-preset $1
    echo "$1" >/tmp/current_preset
    echo "Jamesdsp will be set to $1 preset"
    touch "/tmp/$1"
    remove_file "$2"
  }

  if [[ -n "$cmus_playing" ]] && [[ ! -e "$MUSIC_PATH" ]]; then
    set_preset "$MUSIC_PRESET" "$EQUALIZER_PATH"
  elif [[ -z "$cmus_playing" ]] && [[ ! -e "$EQUALIZER_PATH" ]]; then
    set_preset "$EQUALIZER_PRESET" "$MUSIC_PATH"
  fi
  sleep 2
done
