#!/usr/bin/env bash

# Only exported variables can be used within the timer's command.
export PRIMARY_DISPLAY="$(xrandr | awk '/ primary/{print $1}')"

# Run xidlehook
xidlehook \
  `# Don't lock when there's a fullscreen application` \
  --not-when-fullscreen \
  `# Don't lock when there's audio playing` \
  --not-when-audio \
  `# Dim the screen after 60 seconds, undim if user becomes active` \
  --timer 240 \
  'xrandr --output VGA-1  --brightness 0.25;' \
  'xrandr --output VGA-1  --brightness 0.95;' \
  `# Undim & lock after 10 more seconds` \
  --timer 30 \
  'xrandr --output VGA-1 --brightness 0.95; xset -display :0.0 dpms force off; slock;' \
  'xset -display :0.0 dpms force on' \
  `# Finally, suspend an hour after it locks`
# --timer 3600 \
#   'systemctl hibernate' \
#   'xrandr --output VGA-1 --gamma 1.0:0.88:0.60 --brightness 0.95;'
