#!/bin/sh
CACHE=${XDG_CACHE_HOME:-"$HOME/.cache"}/fuzzel_run
(
  IFS=:
  if test "$(ls -dt $PATH "$CACHE" 2>/dev/null | sed 1q)" != "$CACHE"; then
    mkdir -p "$(dirname "$CACHE")" && lsx-suckless $PATH | sort -u >"$CACHE"
  fi
)
cmd=$(cat $CACHE.fav $CACHE | fuzzel -d "$@") || exit 1
echo $cmd >$CACHE.fav.new
grep -v "^$cmd$" $CACHE.fav >>$CACHE.fav.new
mv $CACHE.fav.new $CACHE.fav
echo "${cmd}"
