#!/usr/bin/env bash
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND="wayland,x11,*"
export SDL_VIDEODRIVER="wayland,x11"
export CLUTTER_BACKEND=wayland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=sway
export XDG_CURRENT_DESKTOP=sway:wlroots
export LIBVA_DRIVER_NAME=i965
export VDPAU_DRIVER=va_gl
export GTK_IM_MODULE=cedilla
export QT_IM_MODULE=cedilla
export GTK_THEME=Nordic-darker
export XCURSOR_THEME=GoogleDot-Nord
export WLR_NO_HARDWARE_CURSORS=1
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export QT_QPA_PLATFORM=wayland-egl
export QT_AUTO_SCREEN_SCALE_FACTOR=1
export QT_QPA_PLATFORMTHEME=qt5ct
export ECORE_EVAS_ENGINE=wayland_egl
export ELM_ENGINE=wayland_egl
export SDL_DYNAMIC_API=/usr/lib/libSDL2-2.0.so
export WLR_DRM_NO_ATOMIC=1

sway
