#!/usr/bin/env bash

# Get focused output name
monitor=$(swaymsg -t get_workspaces | jq -r '.[] | select(.focused).output')

# Define workspace mappings
declare -A workspace_secondary=(
  [w]="1"
  [g]="2"
  [a]="3"
)

declare -A workspace_primary=(
  [w]="4"
  [g]="5"
  [a]="6"
)

# Helper to get workspace based on monitor
get_workspace() {
  local side=$1 # primary or secondary
  local key=$2
  if [[ $side == "primary" ]]; then
    echo "${workspace_primary[$key]}"
  else
    echo "${workspace_secondary[$key]}"
  fi
}

# Define your primary output name (you can customize this)
PRIMARY_OUTPUT="HDMI-A-1" # Change this according to `swaymsg -t get_outputs`

# Determine current/target side
if [[ "$monitor" == "$PRIMARY_OUTPUT" ]]; then
  current_side="primary"
  opposite_side="secondary"
else
  current_side="secondary"
  opposite_side="primary"
fi

# Main logic
case "$1" in
move)
  wks=$(get_workspace "$current_side" "$2")
  swaymsg move container to workspace "$wks"
  ;;
move_in)
  wks=$(get_workspace "$opposite_side" "$2")
  swaymsg move container to workspace "$wks"
  ;;
*)
  wks=$(get_workspace "$current_side" "$1")
  swaymsg workspace "$wks"
  ;;
esac
