#!/usr/bin/env bash

MONITOR=$(i3-msg -t get_tree | jq -r '.. | objects | select(.focused? == true).output'
echo "$MONITOR"

if [[ "$MONITOR" == "VGA1" ]]; then
  pkill -SIGUSR1 herbe
  herbe_secondary _
else
  pkill -SIGUSR1 herbe
  herbe_primary _
fi
