modmap:
  - name: limbo
    application:
      only: limbo
    remap:
      E: UP
      S: LEFT
      D: DOWN
      F: RIGHT
      J: LEFTCTRL
      SPACE: UP
      BTN_LEFT: LEFTCTRL
  
  - name: Global
    remap:
      Alt_R: Super_L
      Capslock:
        held: Control_L # Required, also accepts arrays
        alone: Esc # Required, also accepts arrays
  - name: Warband
    application:
      only: mb_warband_linux
    remap:
      BTN_SIDE: f10
      BTN_EXTRA: f11

keymap:
  - name: xournal
    application:
      only: com.github.xournalpp.xournalpp.Com.github.xournalpp.xournalpp
    remap:
      M-r: C-7

  - name: Zen Browser
    application:
      only: Navigator
    remap:
      Alt_L-l: f6
  - name: tty move
    remap:
      C-i: M-C-f1
      C-o: M-C-f2
