#!/bin/bash
xremap ~/.config/xremap/config.yml &
swww-daemon &
waybar &
pypr &
paplay ~/.audios/retro-audio-logo-94648.mp3 &
systemctl --user import-environment PATH &
dunst &
wl-paste -pw wl-copy &
/usr/lib/polkit-kde-authentication-agent-1 &
swayosd-server &
blueman-applet &
ianny &
sleep 5 && easyeffects --gapplication-service &
