#!/bin/bash
light-keys.sh &
swaybg -i ~/.wallpapers/forrest.png &
waybar &
pypr &
dunst &
flatpak run com.github.wwmm.easyeffects --gapplication-service &
wl-copy &
/usr/lib/polkit-kde-authentication-agent-1 &
wl-paste --watch cliphist store &
swayidle -w \
    timeout 300 'swaylock -i ~/.wallpapers/forrest.png' \
    timeout 600 'hyprctl dispatch dpms off"' \
    resume 'hyprctl dispatch dpms off"' \
    before-sleep 'swaylock -i ~/.wallpapers/forrest.png' &
sway-audio-idle-inhibit &
swayosd-server &
play -q ~/.audios/retro-audio-logo-94648.mp3 &
blueman-applet &
