[pyprland]
plugins = [
  "scratchpads"
]
[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm"
size = "75% 60%"
margin = 50

[scratchpads.whats]
animation = "fromTop"
command = "flatpak run com.github.eneshecan.WhatsAppForLinux"
class = "whatsapp-for-linux"
size = "70% 80%"
process_tracking = false
class_match = true
unfocus = "hide"
lazy = true

[scratchpads.calc]
animation = "fromTop"
command = "galculator"
class = "galculator"
size = "70% 80%"
process_tracking = false
class_match = true
unfocus = "hide"
lazy = true

[scratchpads.todo]
animation = "fromRight"
command = "kuro"
class = "Kuro"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.task-tui]
animation = "fromRight"
command = "foot -T task-tui -a task-tui -e taskwarrior-tui"
class = "task-tui"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.clipse]
animation = "fromRight"
command = "foot -T clipse -a clipse -e clipse"
class = "clipse"
size = "47% 90%"
unfocus = "hide"
lazy = true

[scratchpads.ia]
animation = "fromRight"
command = "alacritty -T ia --class ia -e aichat"
class = "ia"
size = "30% 90%"
position = "65% 5%"
lazy = true

[scratchpads.pulse]
animation = "fromRight"
command = "foot -T pulsemixer -a pulsemixer -e pulsemixer"
class = "pulsemixer"
size = "30% 40%"
position = "65% 5%"
unfocus = "hide"
lazy = true

[scratchpads.stretch]
animation = "fromTop"
command = "flatpak run xyz.safeworlds.hiit"
class = "hiit"
size = "40% 50%"
unfocus = "hide"
process_tracking = false
class_match = true
lazy = true

[scratchpads.canki]
animation = "fromTop"
command = "alacritty -T canki -e ~/.bin/canki.sh"
size = "75% 60%"
margin = 50

[scratchpads.habit]
animation = "fromLeft"
command = "foot -T habit -a habit -e nvim ~/.vimwiki/habit.wiki"
class = "habit"
size = "60% 60%"
margin = 50

[scratchpads.notes]
animation = "fromTop"
command = "foot -T notes -a notes -e nvim ~/.vimwiki/index.md"
class = "notes"
size = "75% 60%"
margin = 50

[scratchpads.btop]
command = "foot -a btop -e btop"
unfocus = "hide"
margin = 100
size = "90% 80%"
position = "5% 10%"
animation = "fromTop"

[scratchpads.bluetui]
command = "foot -a bluetui -e bluetui"
unfocus = "hide"
margin = 100
size = "90% 80%"
position = "5% 10%"
animation = "fromTop"

[scratchpads.tt]
command = "foot -a tt -e tt"
unfocus = "hide"
margin = 100
size = "70% 60%"
animation = "fromTop"

[scratchpads.yazi]
command = "foot -a yazi -e yazi"
unfocus = "hide"
margin = 100
size = "90% 80%"
position = "5% 10%"
animation = "fromTop"

[scratchpads.countdown]
command = "foot -a countdown -e tclock_timer.sh"
unfocus = "hide"
animation = "fromTop"
margin = 200
size = "50% 50%"

