[pyprland]
plugins = [
  "scratchpads",
]
[scratchpads.term]
animation = "fromTop"
command = "alacritty --config-file ~/.config/alacritty/alacritty2.toml --class alacritty-dropterm"
size = "75% 60%"
margin = 50

[scratchpads.task]
command = "foot -a task-tui -e /usr/bin/taskwarrior-tui"
unfocus = "hide"
animation = "fromRight"

[scratchpads.btop]
command = "foot -a btop -e btop"
unfocus = "hide"
margin = 120
size = "90% 70%"
animation = "fromTop"

[scratchpads.neorg]
command = "foot -a neorg -e /usr/bin/nvim -c ':Neorg workspace home'"
animation = "fromBottom"
unfocus = "false"

[scratchpads.countdown]
command = "foot -a countdown -e tclock_timer.sh"
unfocus = "hide"
animation = "fromTop"
margin = 200
size = "50% 50%"

