[pyprland]
plugins = [
  "scratchpads",
  "toggle_dpms",
]
[scratchpads.term]
animation = "fromTop"
command = "alacritty --config-file ~/.config/alacritty/alacritty2.toml --class alacritty-dropterm"
size = "75% 60%"
margin = 50

[scratchpads.canki]
animation = "fromTop"
command = "alacritty -T canki -e ~/.bin/canki.sh"
size = "75% 60%"
margin = 50

[scratchpads.task]
command = "foot -a task-tui -e /usr/bin/taskwarrior-tui"
unfocus = "hide"
animation = "fromRight"

[scratchpads.tt]
command = "foot -a tt -e tt -t 60"
unfocus = "hide"
animation = "fromTop"
size = "90% 70%"
margin = 120

[scratchpads.btop]
command = "foot -a btop -e btop"
unfocus = "hide"
margin = 120
size = "90% 70%"
animation = "fromTop"

[scratchpads.noi]
command = "Noi_linux_0.4.0.AppImage"
unfocus = "hide"
margin = 60
class = "noi"
size = "40% 90%"
animation = "fromRight"

[scratchpads.neorg]
command = "foot -a neorg -e /usr/bin/nvim -c ':Neorg workspace home'"
animation = "fromBottom"
unfocus = "false"

[scratchpads.countdown]
command = "foot -a countdown -e tclock_timer.sh"
unfocus = "hide"
animation = "fromTop"
margin = 200
size = "50% 50%"

