[pyprland]
plugins = [
  "scratchpads"
]
[scratchpads.term]
animation = "fromTop"
command = "alacritty --class alacritty-dropterm --config-file ~/.config/alacritty/scratchpad.toml"
size = "75% 40%"
margin = 40

[scratchpads.whats]
animation = "fromTop"
command = "flatpak run com.github.eneshecan.WhatsAppForLinux"
class = "whatsapp-for-linux"
size = "70% 80%"
process_tracking = false
class_match = true
unfocus = "hide"
lazy = true

[scratchpads.calc]
animation = "fromTop"
command = "foot -T bc -a bc -e bc"
class = "bc"
size = "70% 80%"
process_tracking = false
class_match = true
unfocus = "hide"
lazy = true

[scratchpads.task-tui]
animation = "fromRight"
command = "foot -T task-tui -a task-tui -e taskwarrior-tui"
class = "task-tui"
size = "40% 90%"
unfocus = "hide"
lazy = true

[scratchpads.clipse]
animation = "fromRight"
command = "foot -T clipse -a clipse -e clipse"
class = "clipse"
size = "47% 90%"
unfocus = "hide"
lazy = true

[scratchpads.ia]
animation = "fromRight"
command = "alacritty -T ia --class ia -e aichat"
class = "ia"
size = "30% 90%"
position = "65% 5%"
lazy = true

[scratchpads.pulse]
animation = "fromRight"
command = "foot -T pulsemixer -a pulsemixer -e pulsemixer"
class = "pulsemixer"
size = "30% 40%"
position = "65% 5%"
unfocus = "hide"
lazy = true

[scratchpads.habit]
animation = "fromLeft"
command = "foot -T habit -a habit -e vim ~/.vimwiki/habit.wiki"
class = "habit"
size = "60% 60%"
margin = 50

[scratchpads.notes]
animation = "fromTop"
command = "foot -T notes -a notes -e vim ~/.vimwiki/index.wiki"
class = "notes"
size = "75% 60%"
margin = 50

[scratchpads.btop]
command = "foot -a btop -e btop"
unfocus = "hide"
margin = 100
size = "90% 80%"
position = "5% 10%"
animation = "fromTop"

[scratchpads.yazi]
command = "foot -a yazi -e yazi"
unfocus = "hide"
margin = 100
size = "90% 80%"
position = "5% 10%"
animation = "fromTop"

[scratchpads.countdown]
command = "foot -a countdown -e tclock_timer.sh"
unfocus = "hide"
animation = "fromTop"
margin = 200
size = "50% 50%"

